### ISSUE TITLE
PHP 5.5.9 Ubuntu 14.04 vs PHP 7.0.15 Ubuntu 16.04 

### ISSUE THREAD

**Issue by Globerada** [Minishlink/web-push-php-example#1]
Hi Minishlink.

I have a strange situation trying to send notifications.
Same code over two differents servers.

In PHP 7.0.15 Ubuntu 16.04 works great. 
However, in PHP 5.5.9 Ubuntu 14.04 I get HTTP/1.1 401 Unauthorized from Mozilla and Chrome.

Any idea?

**Comment by Minishlink** [comment]
Hi @Globerada, as you can see in the [requirements](https://github.com/Minishlink/web-push-php-example#requirements), web-push-php is not supported on PHP<5.6, sorry!

**Comment by Globerada** [comment]
You are right.
I am really sorry for don't pay attention to that point.
Thank you for your time. You are great!
