### ISSUE TITLE
Deprecated/Removed extension and functions

### ISSUE THREAD

**Issue by ZherebcovSergey** [Minishlink/web-push-php-example#10]
Hi, in the library there is a function that will be removed in PHP 7.2.0, how will this affect the work?

I [mean](http://php.net/manual/en/function.mcrypt-create-iv.php)
`mcrypt_create_iv ()`
in ".../random_bytes_mcrypt.php" file...

By the way, this also applies to the entire [mcrypt](http://php.net/manual/en/intro.mcrypt.php) extension

**Comment by Minishlink** [comment]
Hello, starting with web-push-php v2.0, the library is compatible with PHP7.2.
