### ISSUE TITLE
notification blocked for your security

### ISSUE THREAD

**Issue by syahnur197** [Minishlink/web-push-php-example#11]
I run the code on my xampp localhost and I tried to access my localhost website from another computer using the same network, but another computer cannot allow the notification because it's blocked for my security. How can I solve this issue?

**Comment by Minishlink** [comment]
It might be blocked because your local server has a self-signed SSL certificate. Disable temporarily the other browser's security if you're developing. If you're in production, switch to a non self-signed  SSL certificate.
