### ISSUE TITLE
Push notifications are not compatible with this browser

### ISSUE THREAD

**Issue by jgatica** [Minishlink/web-push-php-example#12]
The browser shows me this message  "Push notifications are not compatible with this browser". I have a Mac with Mamp Pro and Chrome version 65.0.3325.181 (official Build) (64-bit).

I have configured a VirtualHost http://xxxxx.xx pointing to /Applications/MAMP/htdocs/web-push-php-example/src

------

When I run php-S localhost: 8000 router. php
And I go to the link localhost: 8000 botton for "Enable notifications" is enabled, however the button  "Send a push notification" not working or no appear notification

**Comment by Minishlink** [comment]
Check the console and see what's wrong with your browser's configuration with the [source code](https://github.com/Minishlink/web-push-php-example/blob/53f05d3ef753d50795795199cb75480b73938f92/src/app.js#L71)
