### ISSUE TITLE
Uncaught exception 'RuntimeException' with message 'Curve curve ... does not contain point ...'

### ISSUE THREAD

**Issue by oprachun** [Minishlink/web-push-php-example#2]
Hi. Please help.
Not working example

USER_ERROR Uncaught exception 'RuntimeException' with message 'Curve curve(-3, 41058363725152142129326129780047268409114441015993725554835256314039467401291, 115792089210356248762697446949407573530086143415290314195533631308867097853951) does not contain point (115792089210356248762697446949407573530086143415290314195533631308867097853949, 115792089210356248762697446949407573530086143415290314195533631308867097853950)' in /vendor/mdanter/ecc/src/Primitives/Point.php:100
Stack trace:
#0 /vendor/mdanter/ecc/src/Primitives/CurveFp.php(85): Mdanter\Ecc\Primitives\Point->__construct(Object(Mdanter\Ecc\Math\GmpMath), Object(Mdanter\Ecc\Curves\NamedCurveFp), Resource id #1161, Resource id #1167, true)
#1 /vendor/mdanter/ecc/src/Primitives/Point.php(375): Mdanter\Ecc\Primitives\CurveFp->getPoint(Resource id #1161, Resource id #1167, true)
#2 /vendor/mdanter/ecc/src/Primitives/Point.php(282): Mdanter\Ecc\Primitives\Point->getDouble()
#3 /vendor/mdant
  On line 100 in file /vendor/mdanter/ecc/src/Primitives/Point.php

**Comment by Minishlink** [comment]
Hi @oprachun, do you meet the [requirements](https://github.com/Minishlink/web-push-php-example#requirements)? Have you disabled `mbstring.func_overload` in your PHP config?

**Comment by oprachun** [comment]
Hi. Thank you for help. All is working.
