### ISSUE TITLE
How do you set Options ?

### ISSUE THREAD

**Issue by Sandbird** [Minishlink/web-push-php-example#23]
I've seen some options can be set like 'icon, badge, vibrate etc', but i cant find any way of adding them to the sender. It uses part the serviceworker and part the php...where do you set them ?

**Comment by nomanaadma** [comment]
Can you exactly tell use your scenario.
I am using it in php and serviceWorker.js file 

![image](https://user-images.githubusercontent.com/47977013/67030935-e9cd2680-f129-11e9-8579-271edfa3a162.png)

And this is service worker code 

```const pushUrl = 'https://webpushalert.com/app';

self.addEventListener('push', function (event) {
    if (!(self.Notification && self.Notification.permission === 'granted')) {
        return;
    }
    const sendNotification = body => {

        const content = body.split('@');
        return self.registration.showNotification(content[0], {
            body: content[1],
            icon: content[2],
            data: {
                click_url: content[3]
            },
            tag: Date.now()
        });
    };

    if (event.data) {
        const message = event.data.text();
        event.waitUntil(sendNotification(message));
    }
});
```

I hope you will get it and it will solve your problem

**Comment by Sandbird** [comment]
Yeah i was having problems figuring out how to send stuff from php to the worker. Eventually i figured it out. All work fine besides the 'sound' variable. That doesn't work for some reason. I tried everything i could think of. But its a small price to pay.
I did something similar, send everything in the payload then split them up to the options:

```
<?
$content = array(
	'title' => 'New comment',
	'body' => 'You have a new comment.',
	'icon' => $imagePath.'chat.jpg',
	'badge' => $imagePath.'badge.png',
	'image' => $imagePath.'banner.png',
	'sound' => $soundPath.'notification-sound.mp3',
	'vibrate' => [200, 100, 200, 100, 200, 100, 200],
	'data' => [
		'priority'=>'high',
		'url' => 'https://xxxxx/'
	],
	'actions' => [
		[
		'action' => json_encode(['action'=>'open_url', 'action_url' => 'https://xxxxx/']),
		'title' => 'Open',
		]
	],
	'tag' => 'notify',
	'renotify' => true
);
$pay_load=json_encode($content);
....
$webPush->sendNotification(
    $subscription,
    $pay_load
);
.....

let info = JSON.parse(data);
return self.registration.showNotification( notificationTitle, {
	icon: info.icon,
	badge: info.badge,
	vibrate: info.vibrate,
	image: info.image,
	sound: info.sound,
	tag: info.tag,
	renotify: true,
	data: info.data,
	actions: info.actions,	            
	body: info.body
});

```


Thanks for taking the time to answer.

**Comment by nomanaadma** [comment]
What kind of error are you getting?

**Comment by Sandbird** [comment]
Nothing, no error...there is just no sound playing. Both on PC and android. Tried local path, and also http type location of the file. Maybe because it's an .mp3? I dont know. But i am getting similar notifications on my PC from other places and they do have sound, but i dont know how and why it works with their worker.

**Comment by nomanaadma** [comment]
I think you should open another issue with the sound topic and close this up what do you think?

**Comment by Sandbird** [comment]
Yeah yeah, dont worry about it. Thank for the help  :)
