### ISSUE TITLE
require __DIR__ . '/../vendor/autoload.php';

### ISSUE THREAD

**Issue by abgrxenda** [Minishlink/web-push-php-example#24]
the first line in send_push_notification.php have this line
require __DIR__ . '/../vendor/autoload.php';
where is that file, the send push notification button is not doing any thing

**Comment by EmilAways** [comment]
It's the stupidity of composer and other package-managers. Use Composer to install this, and you will get a vendor-folder with an autoload.php inside. Damn, I miss the good'ol days where you could just unzip stuff and it was ready to roll.

**Comment by abgrxenda** [comment]
sorry for the next question, but when you say composer, what do you mean? is it a dev tool? how to have it or from where to download it?

**Comment by Minishlink** [comment]
https://getcomposer.org/
