### ISSUE TITLE
Works with your router.php and localhost, doesn't with my own local server

### ISSUE THREAD

**Issue by hirasso** [Minishlink/web-push-php-example#3]
Hi, thanks for this great example!

When running from your router.php and localhost:8000, the example works just fine. But when I try to run it inside my own (local) server environment, it doesn't work and I get this error when fetching `send_push_notification.php`:
```
<b>Fatal error</b>:  Call to undefined function Mdanter\Ecc\Curves\gmp_init() in <b>[...my_apache_path...]/web-push-php-example/vendor/mdanter/ecc/src/Curves/NistCurve.php</b> on line <b>133</b><br />
```
I'm not chaning any of the folder structure, just accessing it differently. Any idea what could be causing this? Also, do you know if this should work with self-signed SSL certificates?

**Comment by hirasso** [comment]
Thanks for staying quiet, I figured it out myself. I somehow had a different version of php running in my apache.

**Comment by Minishlink** [comment]
Glad you figured it out :)
