### ISSUE TITLE
Not Working when Browser is closed!!!

### ISSUE THREAD

**Issue by jaedm97** [Minishlink/web-push-php-example#4]
Hello,
This is the best push notification script I ever Found. But I got a problem with this. The problem is - The notification is not sending when the browser is closed. 

Waiting to hear back in a short time.

Thanks

**Comment by Minishlink** [comment]
Hi @jaedm97, which browser are you talking about?
Push notifications can't be received by browsers that are fully closed (ie. it should be either on the foreground with the website opened or not, or as a background process, with no windows opened).

**Comment by jaedm97** [comment]
Thanks for quick reply.
Yes It should work even the Browser is closed. But there should be a process running in the Background.

But in my system when I closed the Browser(checked on Google Chrome and Mozilla Firefox - supported version with Windows 8 OS) there are no process running in the Background for specific browser.

This is why I may not getting Notifications. So can you please tell me is there any way to alive the process even browser is closed?

Waiting to hear back.

Thanks

**Comment by Minishlink** [comment]
I don't know, you may have more luck on StackOverflow.
