### ISSUE TITLE
Mozilla on android | Not working?

### ISSUE THREAD

**Issue by kushubham9** [Minishlink/web-push-php-example#5]
Hi,
I tried to execute this on mozilla android browser. Though the subscription is successful, notifications are not getting delivered.

Does firefox on android not support VAPID? Is FCM essential for it?

V. 54.0.1

I am confused. What role does FCM plays with mobile browsers?

**Comment by Minishlink** [comment]
Hi, please see the discussion https://github.com/web-push-libs/web-push-php/issues/108

With Firefox for Android, FCM is a bridge between the Mozilla's autopush subscription and Google notification system.

**Comment by kushubham9** [comment]
@Minishlink Thanks a lot. It does solve the problem when I disable the padding.

However, I did not get your last part. 
1. Where exactly is FCM coming into play in a typical flow? [I used only VAPID]
2. Can we send notification through FCM without VAPID on android devices?

**Comment by Minishlink** [comment]
1. You don't have to worry about FCM when using web-push-php with VAPID.
2. Yes, but only in Google Chrome for Android, so it's not recommended.
