### ISSUE TITLE
NotificationClick Event on Opera not working

### ISSUE THREAD

**Issue by kushubham9** [Minishlink/web-push-php-example#6]
Hi,
When I add a simple notificationclick event in your service worker, on Opera, when I click on the notification, the event is not getting triggered. 

```
self.addEventListener('notificationclick', function(event) {
    var notificationURL;
    console.log('notification clicled.');
    event.notification.close();
});
```

Do we need to do something here? 
Opera Desktop v 47.

**Comment by Marciobds** [comment]
Hello,

According to mozilla's website opera support to this feature is unknown, opera may not suport onnotificationclick yet.

It is only supported by Chrome >= 42 and Firefox (Gecko) >= 44

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onnotificationclick
https://developer.mozilla.org/pt-BR/docs/Web/API/NotificationEvent
