### ISSUE TITLE
Why push_updateSubscription() after registering service worker?

### ISSUE THREAD

**Issue by R0byn** [Minishlink/web-push-php-example#7]
Hi,
I'm new to the Push API.
I'm wondering why it is necessary to update something at the server side after having registered the service worker (see call of push_updateSubscription() in line 47 of app.js) and what to update?
From my impression the endpoint, token and key seem to be always the same, even after closing and restarting the browser.
Thanks and best regards
R0byn

**Comment by Minishlink** [comment]
Hello @R0byn, sorry for the late reply.
They are in practice the same, but they could still change in the future. ;)
